[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'cancun'


additional_compiler_profiles = [ 
  { name = "london", optimizer_runs = 999999, evm_version = "london" },
]

compilation_restrictions = [
    # london
    { paths = "src/callback/*", evm_version = "london" }
]